#!/usr/bin/env bash

# Create and activate virtual environment
python3 -m venv venv
source venv/bin/activate

apt-get install tesseract-ocr
apt-get install imagemagick
apt-get install libtesseract-dev


# This is temporary
echo ""
echo ""
echo ""
tesseract
echo ""
echo ""
which tesseract
echo ""
echo ""
echo ""

if [ -d "/usr/bin/tesseractr" ]
then
    echo "Directory /usr/bin/tesseract exists. Adding tesseract to PATH"
    PATH=$PATH:"/usr/bin/tesseractr"

    # This is temporary
    echo ""
    echo ""
    echo ""
    tesseract
    echo ""
    echo ""
    which tesseract
    echo ""
    echo ""
    echo ""

else
    echo "Error: Directory /usr/bin/tesseract does not exists. No tesseract this time"
fi



# Install reqs
pip install --upgrade pip && pip install -r requirements.txt

export FLASK_APP=main/app
export FLASK_ENV=development
export FLASK_DEBUG=1

# If "$PORT" is undefined, then call runme with no args, running locally.
# Otherwise, run it with the appropriate args.
if [ -z "$PORT" ]
then
    echo "Running flask locally!"
    python3 runme.py
else
    echo "Running flask in Heroku!"
    python3 runme.py 0.0.0.0 $PORT
fi
