#!/usr/bin/env bash

# Create and activate virtual environment
python3 -m venv venv
source venv/bin/activate

# Install reqs
pip install --upgrade pip && pip install -r requirements.txt

export FLASK_APP=app/main.py
export FLASK_ENV=development

# Run on heroku's "PORT" variable, or 5000 if running locally.
flask run -p ${PORT:-5000}
