DROP TABLE IF EXISTS resident;
DROP TABLE IF EXISTS officer;
DROP TABLE IF EXISTS parcel;

CREATE TABLE resident (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  name TEXT NOT NULL
);

CREATE TABLE officer (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  name TEXT NOT NULL
);

CREATE TABLE parcel (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  resident_id INTEGER NOT NULL,
  delivered TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  collected TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  FOREIGN KEY (resident_id) REFERENCES resident (id)
);
