CREATE TABLE IF NOT EXISTS resident (
  id SERIAL PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
	password VARCHAR(102) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  fullname VARCHAR(70) NOT NULL
);

CREATE TABLE IF NOT EXISTS officer (
  id SERIAL PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
	password VARCHAR(102) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  fullname VARCHAR(70) NOT NULL
);

CREATE TABLE IF NOT EXISTS parcel (
  id SERIAL PRIMARY KEY,
  delivered TIMESTAMP,
  collected TIMESTAMP,
  title VARCHAR(50) NOT NULL,
  resident_id INTEGER REFERENCES resident (id)
);
